server:
  port: 8088
  address: 127.0.0.1
  servlet:
    context-path:
    compression:
      enabled: false
      min-response-size: 2048
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

  tomcat:
    max-swallow-size: -1
  max-http-header-size: 100MB
  error:
    whitelabel:
      enabled: true
    path: /user-error
    include-exception: true
    include-stacktrace: always

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/templates/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ukou?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true

  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password: ''
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:com/modules/**/xml/*Mapper.xml
  type-aliases-package: com.modules.*.entity
  global-config:

    banner: false
    db-config:

      id-type: 4

      table-underline: true
    #configuration:

  quartz:
    job-store-type: jdbc

  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true

  freemarker:

    suffix: .ftl

    content-type: text/html

    charset: UTF-8

    cache: false
    prefer-file-system-access: false

    template-loader-path:
      - classpath:/templates
  mail:
    host: smtp.163.com
    username: vring@foxmail.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.jeecg.modules.system.mapper : debug

cas:
  prefixUrl: http://cas.example.org:8443/cas


lance:
  mail:
    sender: 2500861530@qq.com

